---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/image1/image1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
